to calculate matrix and array based calculation to form package called numpY
numerical python

In [1]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [5]:
arr = np.array(l)

In [6]:
type(arr)

numpy.ndarray

In [7]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [10]:
arr1=np.array([[1,2,3],[2,3,4]])

In [11]:
arr.ndim

1

In [12]:
arr1.ndim

2

In [13]:
arr

array([1, 2, 3, 4, 5])

In [14]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
arr2 = np.matrix(l)
# data stored in matrix becomes a 2 dimensional

In [17]:
arr2.ndim

2

In [19]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [21]:
np.asanyarray(arr2)
# asanyarray cannot convert matrix into an arry since matrix is a subdivision of array

matrix([[1, 2, 3, 4, 5]])

In [23]:
a = arr

In [24]:
a

array([1, 2, 3, 4, 5])

In [25]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr[0] = 100 

In [27]:
arr

array([100,   2,   3,   4,   5])

In [28]:
a
# swallow copy operation

array([100,   2,   3,   4,   5])

In [34]:
b = np.copy(arr)
# create a separate memory and changing in one change in one var will not affect other copy
# decopy concept

In [30]:
b

array([100,   2,   3,   4,   5])

In [31]:
b[0] = 234

In [32]:
b

array([234,   2,   3,   4,   5])

In [33]:
arr

array([100,   2,   3,   4,   5])

In [36]:
# multiple function to create different different arrays
np.fromfunction(lambda i,j : i == j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [37]:
np.fromfunction(lambda i,j : i * j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [39]:
list(i*i for i in range (5))

[0, 1, 4, 9, 16]

In [40]:
iterable = (i*i for i in range (5))

In [41]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [42]:
# string function
np.fromstring('24 45 56',sep =' ')

array([24., 45., 56.])

In [43]:
np.fromstring('24,45,56',sep =',')

array([24., 45., 56.])

In [44]:
arr

array([100,   2,   3,   4,   5])

In [45]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [46]:
arr.ndim

1

In [47]:
arr.size

5

In [48]:
arr1.size

6

In [49]:
arr.shape                                                        

(5,)

In [50]:
arr1.shape

(2, 3)

In [51]:
arr.dtype

dtype('int64')

In [52]:
arr1.dtype

dtype('int64')

In [53]:
list(range(5))

[0, 1, 2, 3, 4]

In [54]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
list(range(0.4,10.5))
#range can only take up integer type values not float

TypeError: 'float' object cannot be interpreted as an integer

In [58]:
np.arange(0.4,10.4,0.1)
# arange alterate of range for float

array([ 0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,  1.1,  1.2,  1.3,  1.4,
        1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,  2.2,  2.3,  2.4,  2.5,
        2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,
        3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,
        4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,
        5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9,
        7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9,  8. ,
        8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9,  9. ,  9.1,
        9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9, 10. , 10.1, 10.2,
       10.3])

In [60]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [62]:
np.logspace(1,5,20,base =2)

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [66]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [67]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [69]:
arr2 = np.ones((3,5))

In [70]:
arr2+5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [71]:
arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [72]:
arr2*4

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [73]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
arr4 = np.eye(3)
#identity matrix is created

In [77]:
import pandas as pd

pd.DataFrame(arr4)

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

In [80]:
np.random.rand(2,3)
# mean and std can be anything

array([[0.81875065, 0.2112707 , 0.93847535],
       [0.35172829, 0.53755704, 0.96100025]])

In [81]:
np.random.randn(2,3)
# mean  =0 and std = 1 this isthe result created by randn function

array([[-1.16898736, -0.16514582,  0.47773954],
       [ 0.34617212, -0.46279208,  1.19127708]])

In [83]:
arr2 = np.random.randint(1,5,(3,4))

In [84]:
arr2

array([[1, 3, 4, 3],
       [4, 2, 1, 3],
       [3, 1, 2, 1]])

In [85]:
arr2.size

12

In [86]:
arr2.shape

(3, 4)

In [87]:
arr2.reshape(2,6)

array([[1, 3, 4, 3, 4, 2],
       [1, 3, 3, 1, 2, 1]])

In [88]:
arr2.reshape(3,6)

ValueError: cannot reshape array of size 12 into shape (3,6)

In [89]:
arr2.reshape(4,-1)

array([[1, 3, 4],
       [3, 4, 2],
       [1, 3, 3],
       [1, 2, 1]])

In [90]:
arr2.reshape(4,-2)

array([[1, 3, 4],
       [3, 4, 2],
       [1, 3, 3],
       [1, 2, 1]])

In [91]:
arr2.reshape(2,2,3)

array([[[1, 3, 4],
        [3, 4, 2]],

       [[1, 3, 3],
        [1, 2, 1]]])

In [95]:
arr1=np.random.randint(1,10,(5,6))

In [96]:
arr1

array([[5, 1, 2, 4, 2, 4],
       [5, 4, 7, 2, 5, 6],
       [1, 9, 4, 7, 5, 2],
       [9, 3, 3, 9, 2, 7],
       [3, 4, 9, 1, 9, 3]])

In [97]:
arr1>8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False, False, False],
       [ True, False, False,  True, False, False],
       [False, False,  True, False,  True, False]])

In [98]:
arr1[arr1>8]

array([9, 9, 9, 9, 9])

In [99]:
arr1

array([[5, 1, 2, 4, 2, 4],
       [5, 4, 7, 2, 5, 6],
       [1, 9, 4, 7, 5, 2],
       [9, 3, 3, 9, 2, 7],
       [3, 4, 9, 1, 9, 3]])

In [100]:
arr1[0]

array([5, 1, 2, 4, 2, 4])

In [101]:
arr1[0,(0,1)]

array([5, 1])

In [106]:
arr1[2:4,[2,3]]

array([[4, 7],
       [3, 9]])

In [108]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [109]:
arr1

array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [110]:
arr2

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [111]:
arr1+arr2

array([[2, 2, 3],
       [4, 4, 3],
       [2, 4, 2]])

In [112]:
arr1-arr2

array([[ 0,  0, -1],
       [ 0,  0,  1],
       [ 0,  0,  0]])

In [114]:
arr1*arr2
#just index multipication

array([[1, 1, 2],
       [4, 4, 2],
       [1, 4, 1]])

In [115]:
# matrix multiplication

arr1@arr2

array([[ 4,  5,  4],
       [ 8, 10,  8],
       [ 6,  7,  5]])

In [116]:
arr1/arr2

array([[1. , 1. , 0.5],
       [1. , 1. , 2. ],
       [1. , 1. , 1. ]])

In [117]:
arr1/0

/tmp/ipykernel_867/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [118]:
# numpy - broadcasting

In [121]:
arr = np.zeros((3,4))

In [123]:
arr+5
#broadcasting 5 to all element

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [124]:
a = np.array([1,2,3,4])

In [126]:
arr+a
# array is added in column wise

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [129]:
b=np.array([[3,4,5]])

In [132]:
arr1 = arr+b.T

In [131]:
b.T

array([[3],
       [4],
       [5]])

In [133]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [134]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [135]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [136]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [137]:
np.min(arr1)

3.0

In [138]:
np.max(arr1)

5.0

In [3]:
arr = np.random.randint(1,10,(4,4))

In [4]:
arr

array([[8, 4, 6, 2],
       [8, 7, 4, 3],
       [1, 9, 7, 8],
       [9, 7, 7, 1]])

In [5]:
arr.reshape(8,2)

array([[8, 4],
       [6, 2],
       [8, 7],
       [4, 3],
       [1, 9],
       [7, 8],
       [9, 7],
       [7, 1]])

In [6]:
arr.T

array([[8, 8, 1, 9],
       [4, 7, 9, 7],
       [6, 4, 7, 7],
       [2, 3, 8, 1]])

In [7]:
arr.flatten()

array([8, 4, 6, 2, 8, 7, 4, 3, 1, 9, 7, 8, 9, 7, 7, 1])

In [10]:
np.expand_dims(arr,axis=1)

array([[[8, 4, 6, 2]],

       [[8, 7, 4, 3]],

       [[1, 9, 7, 8]],

       [[9, 7, 7, 1]]])

In [11]:
np.expand_dims(arr,axis=0)

array([[[8, 4, 6, 2],
        [8, 7, 4, 3],
        [1, 9, 7, 8],
        [9, 7, 7, 1]]])

In [12]:
data = np.array([[1],[2],[3]])

In [13]:
np.squeeze(data)

array([1, 2, 3])

In [14]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [18]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [19]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
# binary operations

In [22]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [23]:
arr1**arr2

array([[      729,        32,         5,    262144],
       [        7,       343,         1, 387420489],
       [       25, 387420489,   2097152,         4]])

In [24]:
~arr1

array([[-10,  -3,  -6,  -5],
       [ -8,  -8,  -2, -10],
       [ -6, -10,  -9,  -5]])

In [25]:
arr1>arr2

array([[ True, False,  True, False],
       [ True,  True, False, False],
       [ True, False,  True,  True]])

In [26]:
# string operation

In [27]:
arr = np.array(['sudh','kumar'])

In [31]:
arr.dtype

dtype('<U5')

In [32]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [33]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [34]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [35]:
# mathematical function

In [36]:
arr1

array([[9, 2, 5, 4],
       [7, 7, 1, 9],
       [5, 9, 8, 4]])

In [37]:
np.sin(arr1)

array([[ 0.41211849,  0.90929743, -0.95892427, -0.7568025 ],
       [ 0.6569866 ,  0.6569866 ,  0.84147098,  0.41211849],
       [-0.95892427,  0.41211849,  0.98935825, -0.7568025 ]])

In [38]:
np.cos(arr1)

array([[-0.91113026, -0.41614684,  0.28366219, -0.65364362],
       [ 0.75390225,  0.75390225,  0.54030231, -0.91113026],
       [ 0.28366219, -0.91113026, -0.14550003, -0.65364362]])

In [39]:
np.tan(arr1)

array([[-0.45231566, -2.18503986, -3.38051501,  1.15782128],
       [ 0.87144798,  0.87144798,  1.55740772, -0.45231566],
       [-3.38051501, -0.45231566, -6.79971146,  1.15782128]])

In [40]:
np.log10(arr1)

array([[0.95424251, 0.30103   , 0.69897   , 0.60205999],
       [0.84509804, 0.84509804, 0.        , 0.95424251],
       [0.69897   , 0.95424251, 0.90308999, 0.60205999]])

In [41]:
np.exp(arr1)

array([[8.10308393e+03, 7.38905610e+00, 1.48413159e+02, 5.45981500e+01],
       [1.09663316e+03, 1.09663316e+03, 2.71828183e+00, 8.10308393e+03],
       [1.48413159e+02, 8.10308393e+03, 2.98095799e+03, 5.45981500e+01]])

In [42]:
np.power(arr1,2)

array([[81,  4, 25, 16],
       [49, 49,  1, 81],
       [25, 81, 64, 16]])

In [43]:
np.mean(arr1)

5.833333333333333

In [44]:
np.median(arr1)

6.0

In [47]:
np.std(arr1)

2.6404965862924765

In [48]:
np.var(arr1)

6.972222222222222

In [49]:
np.max(arr1)

9

In [50]:
# arithmetic operation

In [51]:
arr1

array([[9, 2, 5, 4],
       [7, 7, 1, 9],
       [5, 9, 8, 4]])

In [52]:
arr2

array([[3, 5, 1, 9],
       [1, 3, 3, 9],
       [2, 9, 7, 1]])

In [53]:
arr1-arr2

array([[ 6, -3,  4, -5],
       [ 6,  4, -2,  0],
       [ 3,  0,  1,  3]])

In [55]:
np.subtract(arr1,arr2)

array([[ 6, -3,  4, -5],
       [ 6,  4, -2,  0],
       [ 3,  0,  1,  3]])

In [57]:
np.multiply(arr1,arr2)

array([[27, 10,  5, 36],
       [ 7, 21,  3, 81],
       [10, 81, 56,  4]])

In [59]:
np.mod(arr1,arr2)

array([[0, 2, 0, 4],
       [0, 1, 1, 0],
       [1, 0, 1, 0]])

In [60]:
np.power(arr1,arr2)

array([[      729,        32,         5,    262144],
       [        7,       343,         1, 387420489],
       [       25, 387420489,   2097152,         4]])

In [62]:
np.sqrt(arr1)

array([[3.        , 1.41421356, 2.23606798, 2.        ],
       [2.64575131, 2.64575131, 1.        , 3.        ],
       [2.23606798, 3.        , 2.82842712, 2.        ]])

In [63]:
# statistical function

In [64]:
arr1

array([[9, 2, 5, 4],
       [7, 7, 1, 9],
       [5, 9, 8, 4]])

In [65]:
np.mean(arr1)

5.833333333333333

In [66]:
np.std(arr1)

2.6404965862924765

In [67]:
np.median(arr1)

6.0

In [68]:
# start search and counting function

In [72]:
arr = np.array([8,9,5,5,56,2,3,4,5,6])

In [70]:
arr

array([2, 3, 4, 5, 6])

In [73]:
arr.sort()

In [74]:
np.sort(arr)

array([ 2,  3,  4,  5,  5,  5,  6,  8,  9, 56])

In [75]:
np.searchsorted(arr,6)

6

In [78]:
arr2 = np.array([0,354,568,5412,654,524,896])

In [80]:
np.count_nonzero(arr2)

6

In [81]:
np.where(arr2>0)

(array([1, 2, 3, 4, 5, 6]),)

In [83]:
np.extract(arr>2,arr)

array([ 3,  4,  5,  5,  5,  6,  8,  9, 56])

In [84]:
# byteswapping

In [85]:
arr2

array([   0,  354,  568, 5412,  654,  524,  896])

In [87]:
arr2.byteswap()

array([                   0,  7061925690693648384,  4035788216077385728,
        2599984359876329472, -8214002770370363392,   865254078408556544,
       -9222527611924643840])

In [88]:
arr2.byteswap(True)

array([                   0,  7061925690693648384,  4035788216077385728,
        2599984359876329472, -8214002770370363392,   865254078408556544,
       -9222527611924643840])

In [89]:
# copies and views

In [92]:
arr

array([ 2,  3,  4,  5,  5,  5,  6,  8,  9, 56])

In [93]:
a= np.copy(arr)

In [94]:
b = arr.view()

In [95]:
b

array([ 2,  3,  4,  5,  5,  5,  6,  8,  9, 56])

In [96]:
b[0] = 234

In [97]:
b

array([234,   3,   4,   5,   5,   5,   6,   8,   9,  56])

In [98]:
arr

array([234,   3,   4,   5,   5,   5,   6,   8,   9,  56])

In [99]:
# matrix library

In [101]:
import numpy.matlib as nm

In [103]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [104]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [106]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [108]:
#linear algebra

In [109]:
arr

array([234,   3,   4,   5,   5,   5,   6,   8,   9,  56])

In [111]:
arr1 = np.random.randint([[2,3],[4,5]])

In [115]:
arr2 = np.random.randint([[5,3],[2,3]])

In [113]:
arr1

array([[0, 1],
       [1, 1]])

In [116]:
arr2

array([[4, 1],
       [0, 2]])

In [117]:
np.dot(arr1,arr2)

array([[0, 2],
       [4, 3]])

In [118]:
arr1@arr2

array([[0, 2],
       [4, 3]])

In [120]:
np.unique(arr1)

AttributeError: module 'numpy' has no attribute 'distinct'

In [ ]:
np.concatenate